### PR TITLE
Allow ES6 code #15

### LINKED ISSUE #15: Allow ES6 code
Use something like Babel.

That way, we can have code that is much neater and that will look less quirky.

### PR DESCRIPTION
**Pull request by li-kai**
Fixed #15
1) Update syntax to es6
2) Follow airbnb's eslint styleguide

Notes:
- eslint is a javascript linter to ensure people use and follow javascript rules
- airbnb styleguide is the es6 styleguide maintained and used in airbnb, which is a defacto industry standard for well written javascript

### CODE REVIEW

**Comment by samsontmr** [comment]
When do you use const, var and let?

**Comment by Skaty** [comment]
Const: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/const
Var: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/var
Let: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let

**Review by Skaty — APPROVED** [review]
LGTM! :+1:
Wait for #18.

Also, can integrate with Travis later?

**Comment by Skaty** [comment]
@li-kai Rebase/merge latest changes

**Pull request merged**
